<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students[
<!ELEMENT students (student)+>
<!ELEMENT student (FirstName,MiddleName?,LastName,Grade,ContactNumber)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT ContactNumber (#PCDATA)>
<!ATTLIST students type CDATA #REQUIRED>
]>
<students type ="example">
<student>
    <FirstName>Apeksha</FirstName>
    <MiddleName>Kumari</MiddleName>
    <LastName>Dhungana</LastName>
    <Grade>Bachelor Third Semester</Grade>
    <ContactNumber>
        <ncell> 09876543 </ncell>
        <ntc> 0987654 </ntc>
    </ContactNumber>

</student>
<student>
    <FirstName>Dipika</FirstName>
    <MiddleName>Kumari</MiddleName>
    <LastName>Dhungana</LastName>
    <Grade>Bachelor Third Semester</Grade>
    <ContactNumber>9843530317</ContactNumber>

</student>
</student>